<a href="https://colab.research.google.com/github/oumaklaus/ML-Notes/blob/main/notebooks/clause_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#MODULE 1 - Introduction to NumPy Arrays



In [2]:
import numpy as np
mylist = [2, 3, 4, 5]
print(len(mylist))

4


In [3]:
#Add an element to the list,,,adds to the end
mylist.append(6)
print(mylist)

[2, 3, 4, 5, 6]


In [4]:
#Delete the element of the specified index
del mylist[0]
print(mylist)

[3, 4, 5, 6]


In [5]:
mylist = np.array([3, 4, 5, 6, 6, 6])
print(mylist)

[3 4 5 6 6 6]


In [6]:
arr = np.array([2, 3, 4, 5])
print(arr)

[2 3 4 5]


In [7]:
list1 = [2,3,4,5]

list1 = np.array([2,3,4,5])
print(type(list1))

<class 'numpy.ndarray'>


In [8]:
#2D Arrays
arr = np.array([
    [2,3,4,5,4],
    [3,3,4,5,6]
])
print(arr)

[[2 3 4 5 4]
 [3 3 4 5 6]]


In [9]:
#Show the shape of the array
arr = np.array([
    [2,3,4,5],
    [3,5,7,8]
    ])
print(arr.shape)

(2, 4)


In [10]:
arr = np.array([2,3,4,5,4])
print(arr.shape)

(5,)


In [11]:
#Show the dimensions of the array
arr = np.array([3,4,5,6])
print(arr.ndim)

1


In [12]:
#Find the size of the array
arr = np.array([3,4,5,6])
print(arr.size)

4


In [13]:
#Find the size of the array
arr = np.array([
    [2,3,4,5],
    [3,5,7,8],
    [2,5,6,7]
    ])
print(arr.size)

12


In [14]:
#Find the data type
arr = np.array([3,4,5,6])
print(arr.dtype)

int64


In [15]:
arr = np.array([
    [22,45,32,87],
    [44,74,99,21],
     [407,794,9,24]
])
print(arr[0,2])
print(arr[1,3])
print(arr[2,1])

32
21
794


In [16]:
#modifying an ellement
arr[0,0] = 0
print(arr)

[[  0  45  32  87]
 [ 44  74  99  21]
 [407 794   9  24]]


#Assignment

In [17]:
import numpy as np
arr = np.array([
    [5,10,15],
    [20,25,30]
])
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

(2, 3)
int64
2
6


In [18]:
#Printing 25
arr = np.array([
    [5,10,15],
    [20,25,30]
])
print(arr[1,1])
print(arr[0,2])
arr[1,2] = 300
print(arr)

25
15
[[  5  10  15]
 [ 20  25 300]]


In [19]:
a = np.array([2,4,6])
b = np.array([1,3,5])

print(a+b)
print(a*b)
print(a/b)
print(a-b)

[ 3  7 11]
[ 2 12 30]
[2.         1.33333333 1.2       ]
[1 1 1]


1.


In [20]:
arr = np.random.randint(1,50, size = (3,4))
print(arr.size)
arr[0,0] = 999
arr + 10
print(arr)

12
[[999  28  30   9]
 [ 26  26  11   1]
 [ 23  47   5  34]]


In [21]:
arr = np.array([
    [22,45,32,87],
    [44,74,99,21],
     [407,794,9,24]
])
arr += 10
print(arr)

[[ 32  55  42  97]
 [ 54  84 109  31]
 [417 804  19  34]]


#MODULE 2 - Indexing & Slicing

In [22]:
#Negative indexing
arr1 = np.random.randint(10,100, size = (3,3))
print(arr1)

[[64 88 56]
 [68 33 14]
 [51 95 20]]


In [23]:
print(arr1[-1,-2]) #should print 44
print(arr1[-2,-3]) #should print 83
print(arr1[-1,-1]) #should print 40
print(arr1[-3,-2]) #should print 77

95
68
20
88


In [24]:
#slicing
numbers = np.array([10,20,30,40,50,60,70,80,90])
print(numbers[1:4]) #should print from index 1 to 3. (1 is start : 4 is stop)

[20 30 40]


In [25]:
#Ommiting values
print(numbers[3:]) #print numbers from the specifies index to the end
print(numbers[:3]) #print all numbers from beggining

[40 50 60 70 80 90]
[10 20 30]


In [26]:
print(numbers[::2]) # start from index 0, then add 2 to the index and print the element of that index
print(numbers[::3]) # start from index 0, then add 3 to the index and print the element of that index
print(numbers[1::3]) # start from index 1, then add 3 to the index and print the element of that index
print(numbers[2:8:2]) # start from index 2, stop at index 8, add to 2, to the current index untill you reach the stop index

[10 30 50 70 90]
[10 40 70]
[20 50 80]
[30 50 70]


In [27]:
#Reverse an Array

numbers[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

In [28]:
#Row Slicing
arr = np.array([
    [20,10,40],
    [39,20,45],
    [22,31,43]
])
print(arr[1]) #first row
print(arr[1]) #second row
print(arr[2]) #last row,, can also be written as print(arr[-1])
print(arr[1:]) #rows 1 and 2

[39 20 45]
[39 20 45]
[22 31 43]
[[39 20 45]
 [22 31 43]]


In [29]:
#Column Slicing

#arr[:, 0] #first column
arr[:,0:2] # print the first two columns

array([[20, 10],
       [39, 20],
       [22, 31]])

In [33]:
#Selecting a Subarray
subarr = np.array([
    [20,30,40],
    [50,60,70],
    [80,90,10]
])
subarr[1:,1:]

array([[60, 70],
       [90, 10]])